X_train shape:  torch.Size([2229])
y_train shape:  torch.Size([2229])
X_train dtype:  torch.float32
y_train dtpye:  torch.float32
/home/mira/PycharmProjects/gp_plankton_model/train/train.py:132: DtypeWarning: Columns (66,67,132,133,190) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(train_config["data_path"])
/home/mira/PycharmProjects/gp_plankton_model/train/train.py:113: MatplotlibDeprecationWarning: Support for passing numbers through unit converters is deprecated since 3.5 and support will be removed two minor releases later; use Axis.convert_units instead.
  fig.savefig(train_test_img)
/home/mira/PycharmProjects/gp_plankton_model/train/train.py:113: MatplotlibDeprecationWarning: Support for passing numbers through unit converters is deprecated since 3.5 and support will be removed two minor releases later; use Axis.convert_units instead.
  fig.savefig(train_test_img)
Traceback (most recent call last):
  File "/home/mira/PycharmProjects/gp_plankton_model/train/train.py", line 152, in <module>
    model = models.spectralGP_model.SpectralMixtureGPModel(X_train, y_train, likelihood, config.num_mixtures)
  File "/home/mira/PycharmProjects/gp_plankton_model/models/spectralGP_model.py", line 9, in __init__
    self.covar_module.initialize_from_data(train_x, train_y)
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/gpytorch/kernels/spectral_mixture_kernel.py", line 267, in initialize_from_data
    self.mixture_weights = train_y.std().div(self.num_mixtures)
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/gpytorch/kernels/spectral_mixture_kernel.py", line 150, in mixture_weights
    self._set_mixture_weights(value)
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/gpytorch/kernels/spectral_mixture_kernel.py", line 155, in _set_mixture_weights
    self.initialize(raw_mixture_weights=self.raw_mixture_weights_constraint.inverse_transform(value))
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/gpytorch/module.py", line 103, in initialize
    raise RuntimeError(
RuntimeError: Attempting to manually set a parameter value that is out of bounds of its current constraints, Positive(). Most likely, you want to do the following:
 likelihood = GaussianLikelihood(noise_constraint=gpytorch.constraints.GreaterThan(better_lower_bound))